In [3]:
import pandas as pd
import numpy as np

df_empresas = pd.read_csv('empresas_coletadas.csv', sep=';', encoding='utf-8', low_memory= False) # 'sep=' serve para fazer a separação das colunas da planilha, por exemplo aqui a separação é ";" porém poderia ser apenas ","

display(df_empresas.fillna(0))
# pd.read_excel('gerentes_lojas.xlsx') # pandas faz a

,CNPJ,Razão,Fantasia,Tipo,Endereço,Número,Complemento,Bairro,Cidade,UF,...,Identificador Sócio,Nome do Sócio,Faixa Etária,CPF/CNPJ do Sócio,Qualificação,Data da Entrada,Faturamento Estimado,Quadro de Funcionários,Dívidas Federais Ativas,Total Dívidas
0,20335153000105,HB POOLING EMBALAGENS RETORNAVEIS LTDA.,HB POOLING,RUA,MARIANO TORRES,729,CONJ 702 ANDAR 08 ...,CENTRO,CURITIBA,PR,...,"null, null, null, null, null","null, null, null, null, null","null, null, null, null, null","null, null, null, null, null","null, null, null, null, null","null, null, null, null, null","R$ 50000000,00 a R$ 10000000000,00",ACIMA DE 700 COLABORADORES,0.0,0.0
1,75627836000110,JALOTO TRANSPORTES LTDA,0,AVENIDA,COLOMBO,800,0,PQ INDUSTRIAL II,MARINGA,PR,...,"null, null","null, null","null, null","null, null","null, null","null, null","R$ 4800001,00 a R$ 20000000,00",100 A 500 COLABORADORES,0.0,0.0
2,79045647000190,STATOMAT MAQUINAS ESPECIAIS LTDA,0,RUA,TERRA BOA,960,0,VILA PERNETA,PINHAIS,PR,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 4800001,00 a R$ 20000000,00",100 A 500 COLABORADORES,0.0,0.0
3,75717355000103,USINA DE ACUCAR SANTA TEREZINHA LTDA,0,AVENIDA,PIONEIRO VICTORIO MARCON,693,0,PARQUE INDUSTRIAL II,MARINGA,PR,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 50000000,00 a R$ 10000000000,00",ACIMA DE 700 COLABORADORES,0.0,0.0
4,83388413000112,ESTOFADOS KRAUSE LTDA,0,RUA,RODOLFO HUFENUESSLER,104,0,CENTRO,JARAGUA DO SUL,SC,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 360001,00 a R$ 4800000,00",20 A 99 COLABORADORES,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4494,2007765000189,SERRALHERIA LOPERFER LTDA,LOPERFER,RUA,DEPUTADO LUIZ GABRIEL SAMPAIO,1280,0,GUATUPE,SAO JOSE DOS PINHAIS,PR,...,0,0,0,0,0,0,"R$ 360001,00 a R$ 4800000,00",20 A 99 COLABORADORES,0.0,0.0
4495,2386325000180,PARABELLUM COTURNOS E UNIFORMES LTDA,PARABELLUM,RUA,PROFESSOR JOAO SOARES BARCELOS,2342,0,BOQUEIRAO,CURITIBA,PR,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 4800001,00 a R$ 20000000,00",100 A 500 COLABORADORES,0.0,0.0
4496,67117705000164,INJETAQ INDUSTRIA E COMERCIO LTDA,0,RUA,CAPISTRANO DE ABREU,306,0,JARDIM FRATERNAL,DIADEMA,SP,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 4800001,00 a R$ 20000000,00",100 A 500 COLABORADORES,0.0,0.0
4497,52397767000108,TRANSPORTADORA VERONESE LTDA,0,RUA,DR RAUL DA CUNHA BUENO,1356,SALA 3,CENTRO,MIRANDOPOLIS,SP,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 4800001,00 a R$ 20000000,00",100 A 500 COLABORADORES,0.0,0.0
4498,2417230000186,PACKEM S.A.,0,RODOVIA,SC 350,567,KM 375,SANTA TEREZA,AURORA,SC,...,"null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","null, null, null, null, null, null, null, null...","R$ 4800001,00 a R$ 20000000,00",100 A 500 COLABORADORES,0.0,0.0

In [4]:
# INSPEÇÃO

# display(df_empresas)
# display(df_empresas.head(3)) # .head mostra as linhas iniciais
# display(df_empresas.tail(3)) # .tail mostra as linhas finais
# display(df_empresas.sample(3)) # .sample pega linhas aleatórias da minha planilha
display(df_empresas.shape) # mostra a quantidade de linhas e colunas
# display(list(df_empresas.columns)) 
display(df_empresas.info()) # me mostra as informações de cada coluna
display(df_empresas.describe()) # me trás basicamente os dados estatísticos da planilha

(4499, 44)

<class 'pandas.DataFrame'>
RangeIndex: 4499 entries, 0 to 4498
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CNPJ                       4499 non-null   int64
 1   Razão                      4499 non-null   str
 2   Fantasia                   2370 non-null   str
 3   Tipo                       4475 non-null   str
 4   Endereço                   4499 non-null   str
 5   Número                     4498 non-null   str
 6   Complemento                1662 non-null   str
 7   Bairro                     4499 non-null   str
 8   Cidade                     4499 non-null   str
 9   UF                         4499 non-null   str
 10  Cód. IBGE                  0 non-null      float64
 11  CEP                        4499 non-null   int64
 12  Telefone 1                 4499 non-null   str
 13  Telefone 2                 4499 non-null   str
 14  E-mail                     3961 non-null   str
 15  Site                       3587 non-null   str
 16  CNAE Principal             4499 non-null   str
 17  Texto CNAE Principal       0 non-null      float64
 18  CNAE Secundário            4135 non-null   str
 19  Matriz/Filial              4499 non-null   int64
 20  Ente Federativo            0 non-null      float64
 21  Situação                   4499 non-null   int64
 22  Cód. Situação              0 non-null      float64
 23  Natureza Jurídica          4499 non-null   str
 24  Data Início Ativ.          4499 non-null   int64
 25  Opção pelo MEI             1611 non-null   str
 26  Data entrada MEI           1611 non-null   float64
 27  Data exclusão MEI          1611 non-null   float64
 28  Programas Especiais        4499 non-null   str
 29  Porte Empresa              4499 non-null   int64
 30  Regime Tributário          4499 non-null   str
 31  Data Opção Simples         1611 non-null   float64
 32  Data Exclusão Simples      1611 non-null   float64
 33  Capital Social da Empresa  4499 non-null   int64
 34  Identificador Sócio        3160 non-null   str
 35  Nome do Sócio              3160 non-null   str
 36  Faixa Etária               3160 non-null   str
 37  CPF/CNPJ do Sócio          3160 non-null   str
 38  Qualificação               3160 non-null   str
 39  Data da Entrada            3160 non-null   str
 40  Faturamento Estimado       4499 non-null   str
 41  Quadro de Funcionários     4499 non-null   str
 42  Dívidas Federais Ativas    0 non-null      float64
 43  Total Dívidas              0 non-null      float64
dtypes: float64(10), int64(7), str(27)
memory usage: 1.5 MB

None

,CNPJ,Cód. IBGE,CEP,Texto CNAE Principal,Matriz/Filial,Ente Federativo,Situação,Cód. Situação,Data Início Ativ.,Data entrada MEI,Data exclusão MEI,Porte Empresa,Data Opção Simples,Data Exclusão Simples,Capital Social da Empresa,Dívidas Federais Ativas,Total Dívidas
count,4.499000e+03,0.0,4.499000e+03,0.0,4499.000000,0.0,4499.000000,0.0,4.499000e+03,1.611000e+03,1.611000e+03,4499.000000,1.611000e+03,1.611000e+03,4.499000e+03,0.0,0.0
mean,3.137163e+13,NaN,6.585051e+07,NaN,1.006668,NaN,2.062903,NaN,1.999377e+07,4.006148e+05,4.009804e+05,4.409202,2.012778e+07,1.850470e+07,4.486559e+07,NaN,NaN
std,2.971310e+13,NaN,3.077303e+07,NaN,0.081395,NaN,0.569570,NaN,1.491413e+05,2.815001e+06,2.817570e+06,1.207069,5.635636e+04,5.552969e+06,3.642314e+08,NaN,NaN
min,5.063000e+09,NaN,1.013000e+06,NaN,1.000000,NaN,2.000000,NaN,1.940092e+07,0.000000e+00,0.000000e+00,1.000000,2.007070e+07,0.000000e+00,0.000000e+00,NaN,NaN
25%,5.857598e+12,NaN,3.237164e+07,NaN,1.000000,NaN,2.000000,NaN,1.990113e+07,0.000000e+00,0.000000e+00,5.000000,2.007070e+07,2.010123e+07,1.000000e+05,NaN,NaN
50%,1.861283e+13,NaN,8.305036e+07,NaN,1.000000,NaN,2.000000,NaN,2.001042e+07,0.000000e+00,0.000000e+00,5.000000,2.011081e+07,2.017123e+07,8.200000e+05,NaN,NaN
75%,5.564379e+13,NaN,8.595000e+07,NaN,1.000000,NaN,2.000000,NaN,2.011052e+07,0.000000e+00,0.000000e+00,5.000000,2.018010e+07,2.021123e+07,6.268893e+06,NaN,NaN
max,9.841802e+13,NaN,9.995000e+07,NaN,2.000000,NaN,8.000000,NaN,2.025120e+07,2.022112e+07,2.025093e+07,5.000000,2.026010e+07,2.026053e+07,1.257973e+10,NaN,NaN

In [14]:
# TRATAMENTOS DE DADOS
# list_colums = ['CNPJ', 'Cidade', 'E-mail'] # caso eu queira chamar várias colunas posso utilizar uma variável ou chamando de outra forma na linha de baixo
# display(df_empresas['CNPJ'])
df_empresas_analise = df_empresas[['CNPJ', 'E-mail', 'Cidade', 'Data Início Ativ.', 'Data da Entrada']] # desta forma também posso chamar 2 colunas com [[colunas]]

# COLUNAS
df_empresas_analise.drop(columns=['E-mail']) # excluir uma coluna da minha planilha
# display(df_empresas_analise.fillna(0))

# VALORES NULOS
# df_empresas_analise.dropna() # caso haja uma linha vazia ele exclui a linha por completo

# TIPOS DE DADOS ERRADOS
df_empresas_analise['Data Início Ativ.'] = pd.to_datetime(df_empresas_analise['Data Início Ativ.'], format= '%Y%m%d')

# df_empresas_analise['Data da Entrada'] = pd.to_datetime(df_empresas_analise['Data da Entrada'], format= '%Y%m%d')


# TRATAMENTOS DE DUPLICATAS